# Generated by Django 2.2.4 on 2020-11-30 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='address_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='allows_own_drinks',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='capacity',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='price_per_day',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='price_per_hour',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Cities'),
        ),
        migrations.AlterField(
            model_name='location',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Countries'),
        ),
        migrations.AlterField(
            model_name='location',
            name='post_code',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
