# Generated by Django 2.2.4 on 2020-12-01 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201130_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='image',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
