# Generated by Django 3.1.1 on 2021-01-18 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210115_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='allows_own_drinks',
            field=models.BooleanField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='location',
            name='basic_sound_system',
            field=models.BooleanField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='description',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='image',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='price_per_day',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='price_per_hour',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='professional_sound_system',
            field=models.BooleanField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='location',
            name='serves_alcohol',
            field=models.BooleanField(blank=True, default=0),
        ),
    ]
