# Generated by Django 3.1.1 on 2021-01-18 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210118_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
