# Generated by Django 2.2.4 on 2020-12-02 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_location_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='address',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='address_name',
            new_name='street_address',
        ),
        migrations.RemoveField(
            model_name='events',
            name='name',
        ),
        migrations.AddField(
            model_name='location',
            name='basic_sound_system',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='description',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='professional_sound_system',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='serves_alcohol',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='countries',
            name='country',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='events',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
