# Generated by Django 2.2.4 on 2020-12-02 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20201202_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countries',
            name='country',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
