# Generated by Django 3.1.1 on 2021-01-20 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_countries_cities'),
    ]

    operations = [
        migrations.RenameField(
            model_name='countries_cities',
            old_name='city',
            new_name='city_id',
        ),
        migrations.RenameField(
            model_name='countries_cities',
            old_name='country',
            new_name='country_id',
        ),
    ]
