# Generated by Django 3.1.1 on 2021-01-20 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210120_1915'),
    ]

    operations = [
        migrations.RenameField(
            model_name='countries_cities',
            old_name='city_id',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='countries_cities',
            old_name='country_id',
            new_name='country',
        ),
    ]
