# Generated by Django 3.1.1 on 2021-03-08 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20210308_0123'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Countries_cities',
            new_name='CountriesCities',
        ),
        migrations.AddField(
            model_name='usereventsassoc',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
