# Generated by Django 3.1.1 on 2021-03-08 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20210308_0219'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='sold_out',
            field=models.BooleanField(blank=True, default=0),
        ),
    ]
