# Generated by Django 3.1.1 on 2021-03-12 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20210312_2052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpostcommentsassoc',
            old_name='user_comments',
            new_name='user_comment',
        ),
    ]
