# Generated by Django 3.1.1 on 2021-04-01 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_usersociallogin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersociallogin',
            name='social_login',
        ),
    ]
